In [30]:
import tensorflow as tf


In [31]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test/ 255.0


In [32]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation ='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10),                              
])


In [33]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.56410474,  0.15880474, -0.4561565 , -0.18324059,  0.19523403,
         0.4269012 ,  0.24119614,  0.08927551,  0.48065147,  0.42463574]],
      dtype=float32)

In [34]:
tf.nn.softmax(predictions).numpy()

array([[0.13888904, 0.09260798, 0.0500696 , 0.06578094, 0.09604383,
        0.12108246, 0.10056123, 0.08638778, 0.12776877, 0.12080847]],
      dtype=float32)

In [35]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [36]:
loss_fn(y_train[:1], predictions).numpy()


2.1112835

In [37]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])



In [38]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2941 - accuracy: 0.9143
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1421 - accuracy: 0.9586
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1055 - accuracy: 0.9683
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0882 - accuracy: 0.9722
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0724 - accuracy: 0.9772


In [39]:
model.evaluate(x_test, y_test, verbose=2)


313/313 - 0s - loss: 0.0707 - accuracy: 0.9787


[0.07069556415081024, 0.9786999821662903]

In [40]:
probability_model = tf.keras.Sequential([
                    model,
                    tf.keras.layers.Softmax()                     
])

In [41]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.7587941e-09, 9.2701001e-08, 1.1284256e-05, 2.7078160e-04,
        1.1864238e-11, 1.9705142e-07, 4.0525859e-13, 9.9971503e-01,
        1.0605679e-06, 1.5801073e-06],
       [8.6117975e-09, 3.3466931e-06, 9.9998319e-01, 1.2923655e-05,
        4.7222682e-17, 1.4883143e-08, 1.6378111e-08, 8.2770981e-13,
        4.1940780e-07, 5.5693845e-13],
       [2.5839938e-07, 9.9949741e-01, 6.2094601e-05, 3.5771429e-06,
        6.1733031e-06, 6.9558433e-07, 8.9716668e-06, 3.7423323e-04,
        4.6488211e-05, 6.9263557e-08],
       [9.9993837e-01, 9.8129362e-09, 3.2822674e-05, 4.0232825e-07,
        3.4151472e-07, 2.1286655e-06, 7.4341169e-06, 3.5426081e-06,
        2.4290496e-06, 1.2449720e-05],
       [1.2721609e-05, 9.5175050e-09, 8.4838239e-06, 1.4838358e-07,
        9.8266327e-01, 2.4323883e-06, 5.5145330e-05, 5.0468120e-04,
        5.4559478e-06, 1.6747667e-02]], dtype=float32)>

In [ ]:

# Import PyDrive and associated libraries.
# This only needs to be done once per notebook.
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

# Authenticate and create the PyDrive client.
# This only needs to be done once per notebook.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

# List .txt files in the root.
#
# Search query reference:
# https://developers.google.com/drive/v2/web/search-parameters
listed = drive.ListFile({'q': "title contains '.txt' and 'root' in parents"}).GetList()
for file in listed:
  print('title {}, id {}'.format(file['title'], file['id']))